baseURL = "https://www.bcoskun.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde"
[params]
	themeColor="theme-base-0d"
disqusShortname = "spf13"
googleAnalytics = "UA-19266719-4"

